openapi: 3.0.0
info:
  title: mXSS Test
  version: "1.0"
  description: |
    <math><foo-test><mi><li><table><foo-test><li></li></foo-test><a>
      <style>
        <! ${
      </style>
      }
      <foo-b id="><img src onerror='alert(1)'>">hmm...</foo-b>
    </a></table></li></mi></foo-test></math>
paths: {}
